# Generated by Django 5.0.3 on 2024-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
                ('publication', models.CharField(max_length=10)),
                ('date_of_publish', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
